# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: pypy
          env: TOXENV=pypy
        - python: 3.7
          env: TOXENV=py2-cover,py3-cover,coverage

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - yang@keitheis.org
